name: Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:

  linux:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/messense/cargo-zigbuild:latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install cargo packages
        run: cargo install cargo-deb cargo-generate-rpm

      - name: Install depends
        run: |
          apt update && apt install upx rename wget -y
          mkdir uploads

      - name: Get tag
        if: startsWith(github.ref, 'refs/tags/')
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          # Optionally strip `v` prefix
          strip_v: true
  
      - name: Prebuild package
        id: prebuild
        run: |
          cargo zigbuild --release
          cargo deb --no-build --no-strip
          cargo generate-rpm --payload-compress none

          cargo zigbuild --no-default-features --features launch
          cargo deb --no-build --no-strip
          cargo generate-rpm --payload-compress none

          cargo zigbuild --release --no-default-features --features embed
          cargo deb --no-build --no-strip
          cargo generate-rpm --payload-compress none

          echo "SUCCESS=success" >> $GITHUB_OUTPUT
          
      - name: Build openwrt package
        if: steps.prebuild.outputs.SUCCESS == 'success' && !cancelled() && startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          arch=x86_64 bash +x unpack.sh
          mv bin nas-xunlei-openwrt-x86_64-${{ steps.tag.outputs.tag }}
          cargo zigbuild --release --target=x86_64-unknown-linux-musl --no-default-features --features launch
          mv target/x86_64-unknown-linux-musl/release/xunlei nas-xunlei-openwrt-x86_64-${{ steps.tag.outputs.tag }}/
          tar -cf - nas-xunlei-openwrt-x86_64-${{ steps.tag.outputs.tag }} | xz -9 -c - > nas-xunlei-openwrt-x86_64-${{ steps.tag.outputs.tag }}.tar.xz
          mv nas-xunlei-openwrt-x86_64-${{ steps.tag.outputs.tag }}.tar.xz uploads/

          arch=aarch64 bash +x unpack.sh
          mv bin nas-xunlei-openwrt-aarch64-${{ steps.tag.outputs.tag }}
          cargo zigbuild --release --target=aarch64-unknown-linux-musl --no-default-features --features launch
          mv target/aarch64-unknown-linux-musl/release/xunlei nas-xunlei-openwrt-aarch64-${{ steps.tag.outputs.tag }}/
          tar -cf - nas-xunlei-openwrt-aarch64-${{ steps.tag.outputs.tag }} | xz -9 -c - > nas-xunlei-openwrt-aarch64-${{ steps.tag.outputs.tag }}.tar.xz
          mv nas-xunlei-openwrt-aarch64-${{ steps.tag.outputs.tag }}.tar.xz uploads/


      - name: Build x86_64-unknown-linux-gnu package
        if: steps.prebuild.outputs.SUCCESS == 'success' && !cancelled() && startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          root=$(pwd)

          cargo zigbuild --release --target=x86_64-unknown-linux-gnu
          upx target/x86_64-unknown-linux-gnu/release/xunlei
          cargo deb --target=x86_64-unknown-linux-gnu --no-build --no-strip
          cargo generate-rpm --target=x86_64-unknown-linux-gnu --payload-compress none
          cd target/x86_64-unknown-linux-gnu/release
            tar czvf xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu.tar.gz xunlei
            shasum -a 256 xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu.tar.gz > xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu.tar.gz.sha256
            mv xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu.tar.gz $root/uploads/
            mv xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu.tar.gz.sha256 $root/uploads/
          cd -
          mv target/x86_64-unknown-linux-gnu/debian/* $root/uploads/
          mv target/x86_64-unknown-linux-gnu/generate-rpm/* $root/uploads/

          cargo zigbuild --release --target=x86_64-unknown-linux-gnu --no-default-features --features launch
          upx target/x86_64-unknown-linux-gnu/release/xunlei
          cargo deb --target=x86_64-unknown-linux-gnu --no-build --no-strip
          cargo generate-rpm --target=x86_64-unknown-linux-gnu --payload-compress none
          cd target/x86_64-unknown-linux-gnu/release
            tar czvf xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu-launch.tar.gz xunlei
            shasum -a 256 xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu-launch.tar.gz > xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu-launch.tar.gz.sha256
            mv xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu-launch.tar.gz $root/uploads/
            mv xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu-launch.tar.gz.sha256 $root/uploads/
          cd -
          cd target/x86_64-unknown-linux-gnu/debian
            rename 's/xunlei/xunlei-launch/' xunlei*.deb
            mv ./* $root/uploads/
          cd -
          cd target/x86_64-unknown-linux-gnu/generate-rpm
            rename 's/xunlei/xunlei-launch/' xunlei*.rpm
            mv ./* $root/uploads/
          cd -
 
          bash +x unpack.sh && cargo zigbuild --release --target=x86_64-unknown-linux-gnu --no-default-features --features embed
          upx target/x86_64-unknown-linux-gnu/release/xunlei
          cargo deb --target=x86_64-unknown-linux-gnu --no-build --no-strip
          cargo generate-rpm --target=x86_64-unknown-linux-gnu --payload-compress none
          cd target/x86_64-unknown-linux-gnu/release
            tar czvf xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu-embed.tar.gz xunlei
            shasum -a 256 xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu-embed.tar.gz > xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu-embed.tar.gz.sha256
            mv xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu-embed.tar.gz $root/uploads/
            mv xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-gnu-embed.tar.gz.sha256 $root/uploads/
          cd -
          cd target/x86_64-unknown-linux-gnu/debian
            rename 's/xunlei/xunlei-embed/' xunlei*.deb
            mv ./* $root/uploads/
          cd -
          cd target/x86_64-unknown-linux-gnu/generate-rpm
            rename 's/xunlei/xunlei-embed/' xunlei*.rpm
            mv ./* $root/uploads/
          cd -

          ls -lah uploads

      - name: Build x86_64-unknown-linux-musl package
        if: steps.prebuild.outputs.SUCCESS == 'success' && !cancelled() && startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          root=$(pwd)

          cargo zigbuild --release --target=x86_64-unknown-linux-musl
          upx target/x86_64-unknown-linux-musl/release/xunlei
          cargo deb --target=x86_64-unknown-linux-musl --no-build --no-strip
          cargo generate-rpm --target=x86_64-unknown-linux-musl --payload-compress none
          cd target/x86_64-unknown-linux-musl/release
            tar czvf xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl.tar.gz xunlei
            shasum -a 256 xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl.tar.gz > xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl.tar.gz.sha256
            mv xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl.tar.gz $root/uploads/
            mv xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl.tar.gz.sha256 $root/uploads/
          cd -
          mv target/x86_64-unknown-linux-musl/debian/* $root/uploads/
          mv target/x86_64-unknown-linux-musl/generate-rpm/* $root/uploads/

          cargo zigbuild --release --target=x86_64-unknown-linux-musl --no-default-features --features launch
          upx target/x86_64-unknown-linux-musl/release/xunlei
          cargo deb --target=x86_64-unknown-linux-musl --no-build --no-strip
          cargo generate-rpm --target=x86_64-unknown-linux-musl --payload-compress none
          cd target/x86_64-unknown-linux-musl/release
            tar czvf xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl-launch.tar.gz xunlei
            shasum -a 256 xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl-launch.tar.gz > xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl-launch.tar.gz.sha256
            mv xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl-launch.tar.gz $root/uploads/
            mv xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl-launch.tar.gz.sha256 $root/uploads/
          cd -
          cd target/x86_64-unknown-linux-musl/debian
            rename 's/xunlei/xunlei-launch/' xunlei*.deb
            mv ./* $root/uploads/
          cd -
          cd target/x86_64-unknown-linux-musl/generate-rpm
            rename 's/xunlei/xunlei-launch/' xunlei*.rpm
            mv ./* $root/uploads/
          cd -
 
          bash +x unpack.sh && cargo zigbuild --release --target=x86_64-unknown-linux-musl --no-default-features --features embed
          upx target/x86_64-unknown-linux-musl/release/xunlei
          cargo deb --target=x86_64-unknown-linux-musl --no-build --no-strip
          cargo generate-rpm --target=x86_64-unknown-linux-musl --payload-compress none
          cd target/x86_64-unknown-linux-musl/release
            tar czvf xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl-embed.tar.gz xunlei
            shasum -a 256 xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl-embed.tar.gz > xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl-embed.tar.gz.sha256
            mv xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl-embed.tar.gz $root/uploads/
            mv xunlei-${{ steps.tag.outputs.tag }}.x86_64-unknown-linux-musl-embed.tar.gz.sha256 $root/uploads/
          cd -
          cd target/x86_64-unknown-linux-musl/debian
            rename 's/xunlei/xunlei-embed/' xunlei*.deb
            mv ./* $root/uploads/
          cd -
          cd target/x86_64-unknown-linux-musl/generate-rpm
            rename 's/xunlei/xunlei-embed/' xunlei*.rpm
            mv ./* $root/uploads/
          cd -

          ls -lah uploads

      - name: Build aarch64-unknown-linux-gnu package
        if: steps.prebuild.outputs.SUCCESS == 'success' && !cancelled() && startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          root=$(pwd)

          cargo zigbuild --release --target=aarch64-unknown-linux-gnu
          upx target/aarch64-unknown-linux-gnu/release/xunlei
          cargo deb --target=aarch64-unknown-linux-gnu --no-build --no-strip
          cargo generate-rpm --target=aarch64-unknown-linux-gnu --payload-compress none
          cd target/aarch64-unknown-linux-gnu/release
            tar czvf xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu.tar.gz xunlei
            shasum -a 256 xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu.tar.gz > xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu.tar.gz.sha256
            mv xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu.tar.gz $root/uploads/
            mv xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu.tar.gz.sha256 $root/uploads/
          cd -
          mv target/aarch64-unknown-linux-gnu/debian/* $root/uploads/
          mv target/aarch64-unknown-linux-gnu/generate-rpm/* $root/uploads/

          cargo zigbuild --release --target=aarch64-unknown-linux-gnu --no-default-features --features launch
          upx target/aarch64-unknown-linux-gnu/release/xunlei
          cargo deb --target=aarch64-unknown-linux-gnu --no-build --no-strip
          cargo generate-rpm --target=aarch64-unknown-linux-gnu --payload-compress none
          cd target/aarch64-unknown-linux-gnu/release
            tar czvf xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu-launch.tar.gz xunlei
            shasum -a 256 xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu-launch.tar.gz > xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu-launch.tar.gz.sha256
            mv xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu-launch.tar.gz $root/uploads/
            mv xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu-launch.tar.gz.sha256 $root/uploads/
          cd -
          cd target/aarch64-unknown-linux-gnu/debian
            rename 's/xunlei/xunlei-launch/' xunlei*.deb
            mv ./* $root/uploads/
          cd -
          cd target/aarch64-unknown-linux-gnu/generate-rpm
            rename 's/xunlei/xunlei-launch/' xunlei*.rpm
            mv ./* $root/uploads/
          cd -
 
          arch=aarch64 bash +x unpack.sh && cargo zigbuild --release --target=aarch64-unknown-linux-gnu --no-default-features --features embed
          upx target/aarch64-unknown-linux-gnu/release/xunlei
          cargo deb --target=aarch64-unknown-linux-gnu --no-build --no-strip
          cargo generate-rpm --target=aarch64-unknown-linux-gnu --payload-compress none
          cd target/aarch64-unknown-linux-gnu/release
            tar czvf xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu-embed.tar.gz xunlei
            shasum -a 256 xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu-embed.tar.gz > xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu-embed.tar.gz.sha256
            mv xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu-embed.tar.gz $root/uploads/
            mv xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-gnu-embed.tar.gz.sha256 $root/uploads/
          cd -
          cd target/aarch64-unknown-linux-gnu/debian
            rename 's/xunlei/xunlei-embed/' xunlei*.deb
            mv ./* $root/uploads/
          cd -
          cd target/aarch64-unknown-linux-gnu/generate-rpm
            rename 's/xunlei/xunlei-embed/' xunlei*.rpm
            mv ./* $root/uploads/
          cd -

          ls -lah uploads

      - name: Build aarch64-unknown-linux-musl package
        if: steps.prebuild.outputs.SUCCESS == 'success' && !cancelled() && startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          root=$(pwd)

          cargo zigbuild --release --target=aarch64-unknown-linux-musl
          upx target/aarch64-unknown-linux-musl/release/xunlei
          cargo deb --target=aarch64-unknown-linux-musl --no-build --no-strip
          cargo generate-rpm --target=aarch64-unknown-linux-musl --payload-compress none
          cd target/aarch64-unknown-linux-musl/release
            tar czvf xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl.tar.gz xunlei
            shasum -a 256 xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl.tar.gz > xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl.tar.gz.sha256
            mv xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl.tar.gz $root/uploads/
            mv xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl.tar.gz.sha256 $root/uploads/
          cd -
          mv target/aarch64-unknown-linux-musl/debian/* $root/uploads/
          mv target/aarch64-unknown-linux-musl/generate-rpm/* $root/uploads/

          cargo zigbuild --release --target=aarch64-unknown-linux-musl --no-default-features --features launch
          upx target/aarch64-unknown-linux-musl/release/xunlei
          cargo deb --target=aarch64-unknown-linux-musl --no-build --no-strip
          cargo generate-rpm --target=aarch64-unknown-linux-musl --payload-compress none
          cd target/aarch64-unknown-linux-musl/release
            tar czvf xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl-launch.tar.gz xunlei
            shasum -a 256 xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl-launch.tar.gz > xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl-launch.tar.gz.sha256
            mv xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl-launch.tar.gz $root/uploads/
            mv xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl-launch.tar.gz.sha256 $root/uploads/
          cd -
          cd target/aarch64-unknown-linux-musl/debian
            rename 's/xunlei/xunlei-launch/' xunlei*.deb
            mv ./* $root/uploads/
          cd -
          cd target/aarch64-unknown-linux-musl/generate-rpm
            rename 's/xunlei/xunlei-launch/' xunlei*.rpm
            mv ./* $root/uploads/
          cd -
 
          arch=aarch64 bash +x unpack.sh && cargo zigbuild --release --target=aarch64-unknown-linux-musl --no-default-features --features embed
          upx target/aarch64-unknown-linux-musl/release/xunlei
          cargo deb --target=aarch64-unknown-linux-musl --no-build --no-strip
          cargo generate-rpm --target=aarch64-unknown-linux-musl --payload-compress none
          cd target/aarch64-unknown-linux-musl/release
            tar czvf xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl-embed.tar.gz xunlei
            shasum -a 256 xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl-embed.tar.gz > xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl-embed.tar.gz.sha256
            mv xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl-embed.tar.gz $root/uploads/
            mv xunlei-${{ steps.tag.outputs.tag }}.aarch64-unknown-linux-musl-embed.tar.gz.sha256 $root/uploads/
          cd -
          cd target/aarch64-unknown-linux-musl/debian
            rename 's/xunlei/xunlei-embed/' xunlei*.deb
            mv ./* $root/uploads/
          cd -
          cd target/aarch64-unknown-linux-musl/generate-rpm
            rename 's/xunlei/xunlei-embed/' xunlei*.rpm
            mv ./* $root/uploads/
          cd -

          ls -lah uploads

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.TOKEN }}
          files: |
            uploads/*
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          generate_release_notes: true

      - name: Remove cached deb and RPM packages
        run: |
          rm -rf target/x86_64-unknown-linux-gnu/debian
          rm -rf target/x86_64-unknown-linux-gnu/generate-rpm