name: Update xunlei version

on:
  workflow_dispatch:
  schedule:
    # Run every day
    - cron: '0 0 * * *'

jobs:
  update:
    name: Update xunlei version
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/gngpp/linux:ubuntu22.04
    steps:
    - uses: actions/checkout@v3

    - name: Update
      id: update
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        bash +x unpack.sh x86_64
        current_version=$(git describe --tags --abbrev=0 | sed 's/^v//' | sed 's/-.*//')
        new_version=$(cat bin/version)
        sed -i 's/$current_version/$new_version/g' Cargo.toml
        sed -i 's/$current_version/$new_version/g' openwrt/xunlei/Makefile
        echo "new_version=$new_version" >> $GITHUB_ENV
        echo "new_version=$new_version" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: update-xunlei-version
        delete-branch: true
        add-paths: |
          Cargo.toml
          openwrt/xunlei/Makefile
        title: 'Update xunlei to v${{ steps.update.outputs.new_version }}'
        commit-message: 'Update xunlei to v${{ steps.update.outputs.new_version }}'