name: Update xunlei version

on:
  workflow_dispatch:
  schedule:
    # Run every day
    - cron: '0 0 * * *'

jobs:
  update:
    name: Update xunlei version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update version
      run: |
        bash +x check_update.sh

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.TOKEN }}
        branch: update-xunlei-version
        delete-branch: true
        add-paths: |
          Cargo.toml
          Cargo.lock
          openwrt/xunlei/Makefile
          README.md
        title: 'Update xunlei to v${{ steps.update.outputs.new_version }}'
        commit-message: 'Update xunlei to v${{ steps.update.outputs.new_version }}'